### api1
get http://localhost:3000/todos/?status=TO%20DO
Content-Type:application/json

get http://localhost:3000/todos/?priority=HIG
Content-Type:application/json

get http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
Content-Type:application/json

get http://localhost:3000/todos/?search_q=Bu
Content-Type:application/json

get http://localhost:3000/todos/?category=WORK&status=DONE
Content-Type:application/json

get http://localhost:3000/todos/?category=HOM
Content-Type:application/json
### ccbp submit NJSCADOQBS
get http://localhost:3000/todos/?category=LEARNING&priority=HIGH
Content-Type:application/json

### api2


get http://localhost:3000/todos/1
Content-Type:application/json

### api3
get http://localhost:3000/agenda/?date=2021-1-1
Content-Type:application/json

### api4

post http://localhost:3000/todos/
Content-Type:application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###api5

put http://localhost:3000/todos/1
Content-Type:application/json

{
  "status": "DONE"
}


put http://localhost:3000/todos/1
Content-Type:application/json

{
  "priority": "HIGH"
}


put http://localhost:3000/todos/1
Content-Type:application/json

{
  "todo": "Clean the garden"
}

put http://localhost:3000/todos/1
Content-Type:application/json

{
  "category": "LEARNING"
}



put http://localhost:3000/todos/1
Content-Type:application/json

{
  "dueDate": "2021-01-12"
}

###api6

delete http://localhost:3000/todos/6
